name: cosork
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2023.11.17=hbcca054_0
  - cuda=12.3.1=0
  - cuda-cccl=12.3.101=0
  - cuda-command-line-tools=12.3.1=0
  - cuda-compiler=12.3.1=0
  - cuda-cudart=12.3.101=0
  - cuda-cudart-dev=12.3.101=0
  - cuda-cudart-static=12.3.101=0
  - cuda-cuobjdump=12.3.101=0
  - cuda-cupti=12.3.101=0
  - cuda-cupti-static=12.3.101=0
  - cuda-cuxxfilt=12.3.101=0
  - cuda-demo-suite=12.3.101=0
  - cuda-documentation=12.3.101=0
  - cuda-driver-dev=12.3.101=0
  - cuda-gdb=12.3.101=0
  - cuda-libraries=12.3.1=0
  - cuda-libraries-dev=12.3.1=0
  - cuda-libraries-static=12.3.1=0
  - cuda-nsight=12.3.101=0
  - cuda-nsight-compute=12.3.1=0
  - cuda-nvcc=12.3.103=0
  - cuda-nvdisasm=12.3.101=0
  - cuda-nvml-dev=12.3.101=0
  - cuda-nvprof=12.3.101=0
  - cuda-nvprune=12.3.101=0
  - cuda-nvrtc=12.3.103=0
  - cuda-nvrtc-dev=12.3.103=0
  - cuda-nvrtc-static=12.3.103=0
  - cuda-nvtx=12.3.101=0
  - cuda-nvvp=12.3.101=0
  - cuda-opencl=12.3.101=0
  - cuda-opencl-dev=12.3.101=0
  - cuda-profiler-api=12.3.101=0
  - cuda-runtime=12.3.1=0
  - cuda-sanitizer-api=12.3.101=0
  - cuda-toolkit=12.3.1=0
  - cuda-tools=12.3.1=0
  - cuda-visual-tools=12.3.1=0
  - gds-tools=1.8.1.2=0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libcublas=12.3.4.1=0
  - libcublas-dev=12.3.4.1=0
  - libcublas-static=12.3.4.1=0
  - libcufft=11.0.12.1=0
  - libcufft-dev=11.0.12.1=0
  - libcufft-static=11.0.12.1=0
  - libcufile=1.8.1.2=0
  - libcufile-dev=1.8.1.2=0
  - libcufile-static=1.8.1.2=0
  - libcurand=10.3.4.101=0
  - libcurand-dev=10.3.4.101=0
  - libcurand-static=10.3.4.101=0
  - libcusolver=11.5.4.101=0
  - libcusolver-dev=11.5.4.101=0
  - libcusolver-static=11.5.4.101=0
  - libcusparse=12.2.0.103=0
  - libcusparse-dev=12.2.0.103=0
  - libcusparse-static=12.2.0.103=0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgomp=13.2.0=h807b86a_3
  - libnpp=12.2.3.2=0
  - libnpp-dev=12.2.3.2=0
  - libnpp-static=12.2.3.2=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.3.101=0
  - libnvjitlink-dev=12.3.101=0
  - libnvjpeg=12.3.0.81=0
  - libnvjpeg-dev=12.3.0.81=0
  - libnvjpeg-static=12.3.0.81=0
  - libsqlite=3.44.2=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=h59595ed_2
  - nsight-compute=2023.3.1.1=0
  - openssl=3.2.0=hd590300_1
  - pip=23.3.2=pyhd8ed1ab_0
  - python=3.10.13=hd12c33a_1_cpython
  - readline=8.2=h8228510_1
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.21.0
      - aiohttp==3.9.1
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - alembic==1.14.0
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - antlr4-python3-runtime==4.9.3
      - anyio==4.2.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.1.0
      - autogluon==1.1.1
      - autogluon-common==1.1.1
      - autogluon-core==1.1.1
      - autogluon-features==1.1.1
      - autogluon-multimodal==1.1.1
      - autogluon-tabular==1.1.1
      - autogluon-timeseries==1.1.1
      - backoff==2.2.1
      - beautifulsoup4==4.12.2
      - blessed==1.20.0
      - blis==0.7.11
      - boto3==1.34.11
      - botocore==1.34.11
      - cachetools==5.3.2
      - catalogue==2.0.10
      - catboost==1.2.2
      - certifi==2022.12.7
      - cffi==1.16.0
      - charset-normalizer==2.1.1
      - chord==6.0.1
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cloudpickle==3.0.0
      - cmake==3.25.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorful==0.5.5
      - colorlog==6.9.0
      - comm==0.2.0
      - confection==0.1.4
      - contourpy==1.2.0
      - crcmod==1.7
      - croniter==1.4.1
      - cryptography==41.0.7
      - cycler==0.12.1
      - cymem==2.0.8
      - dask==2024.1.0
      - datasets==2.16.1
      - dateutils==0.6.12
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepdiff==6.7.1
      - defusedxml==0.7.1
      - derivative==0.6.0
      - dill==0.3.7
      - distlib==0.3.8
      - distributed==2024.1.0
      - docker-pycreds==0.4.0
      - drawsvg==2.4.0
      - et-xmlfile==1.1.0
      - evaluate==0.4.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastai==2.7.17
      - fastapi==0.108.0
      - fastcore==1.5.29
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - filelock==3.9.0
      - flatbuffers==23.5.26
      - fonttools==4.47.0
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - future==0.18.3
      - gast==0.5.4
      - gdown==4.7.1
      - gitdb==4.0.11
      - gitpython==3.1.41
      - gluonts==0.15.1
      - google-api-core==2.15.0
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.62.0
      - gpustat==1.1.1
      - greenlet==3.1.1
      - grpcio==1.60.0
      - h11==0.14.0
      - h5py==3.10.0
      - huggingface-hub==0.20.1
      - humanfriendly==10.0
      - hyperopt==0.2.7
      - idna==3.4
      - imageio==2.33.1
      - imbalanced-learn==0.12.4
      - importlib-metadata==7.0.1
      - inquirer==3.1.4
      - ipykernel==6.28.0
      - ipython==8.19.0
      - ipywidgets==8.1.1
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - jmespath==0.10.0
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.0
      - jupyter-core==5.5.1
      - jupyterlab-widgets==3.0.9
      - keras==2.15.0
      - keras-tuner==1.4.6
      - kiwisolver==1.4.5
      - kt-legacy==1.0.5
      - langcodes==3.3.0
      - lazy-loader==0.3
      - libclang==16.0.6
      - lightgbm==4.1.0
      - lightning==2.3.3
      - lightning-cloud==0.5.57
      - lightning-utilities==0.10.0
      - lit==15.0.7
      - llvmlite==0.41.1
      - locket==1.0.0
      - mako==1.3.8
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - mlforecast==0.10.0
      - model-index==0.1.11
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.15
      - murmurhash==1.0.10
      - nest-asyncio==1.5.8
      - networkx==3.0
      - nlpaug==1.1.11
      - nltk==3.8.1
      - nptyping==2.4.1
      - numba==0.58.1
      - numexpr==2.8.8
      - numpy==1.24.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.133
      - nvidia-ml-py3==7.352.0
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - odeformer==0.1.5
      - omegaconf==2.2.3
      - onnx==1.16.2
      - onnxruntime==1.19.0
      - opencensus==0.11.3
      - opencensus-context==0.1.3
      - openchord==0.1.7
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.5
      - openxlab==0.0.32
      - opt-einsum==3.3.0
      - optimum==1.18.1
      - optuna==4.1.0
      - ordered-set==4.1.0
      - orjson==3.9.10
      - oss2==2.17.0
      - packaging==23.2
      - pandas==2.1.4
      - parso==0.8.3
      - partd==1.4.1
      - patsy==0.5.5
      - pdf2image==1.17.0
      - pexpect==4.9.0
      - pillow==10.1.0
      - platformdirs==3.11.0
      - plotapi==8.0.0
      - plotly==5.18.0
      - preshed==3.0.9
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.43
      - protobuf==4.23.4
      - psutil==5.9.7
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-spy==0.3.14
      - py4j==0.10.9.7
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycatch22==0.4.4
      - pycparser==2.21
      - pycryptodome==3.19.1
      - pydantic==1.10.13
      - pygments==2.17.2
      - pygraphviz==1.12
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - pyrsistent==0.20.0
      - pysindy==1.7.5
      - pysocks==1.7.1
      - pytesseract==0.3.10
      - python-dateutil==2.8.2
      - python-editor==1.0.4
      - graphviz==0.20.1
      - python-multipart==0.0.6
      - pytorch-lightning==2.3.3
      - pytorch-metric-learning==1.7.3
      - pyts==0.13.0
      - pytz==2023.3.post1
      - pywavelets==1.5.0
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - ray==2.10.0
      - readchar==4.0.5
      - referencing==0.35.1
      - regex==2023.12.25
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rich==13.4.2
      - rpds-py==0.20.0
      - rsa==4.9
      - s3transfer==0.10.0
      - safetensors==0.4.1
      - scikit-image==0.20.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - scs==3.2.4.post1
      - seaborn==0.13.1
      - sentencepiece==0.1.99
      - sentry-sdk==1.39.2
      - seqeval==1.2.2
      - setproctitle==1.3.3
      - setuptools==60.2.0
      - six==1.16.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.36
      - srsly==2.4.8
      - stack-data==0.6.3
      - starlette==0.32.0.post1
      - starsessions==1.3.0
      - statsforecast==1.4.0
      - statsmodels==0.14.1
      - stumpy==1.12.0
      - sympy==1.11.1
      - tabulate==0.9.0
      - tblib==3.0.0
      - tenacity==8.2.3
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.15.0.post1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.35.0
      - termcolor==2.4.0
      - text-unidecode==1.3
      - thinc==8.2.2
      - threadpoolctl==3.2.0
      - tifffile==2023.12.9
      - timm==0.9.12
      - tokenizers==0.15.2
      - toolz==0.12.0
      - torch==2.2.2
      - torchdiffeq==0.2.4
      - torchmetrics==1.2.1
      - torchvision==0.17.2
      - tornado==6.4
      - tqdm==4.65.2
      - traitlets==5.14.0
      - transformers==4.39.3
      - triton==2.2.0
      - tsai==0.3.9
      - tsfresh==0.20.1
      - typer==0.9.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - urllib3==1.26.13
      - utilsforecast==0.0.10
      - uvicorn==0.25.0
      - virtualenv==20.21.0
      - wandb==0.16.2
      - wasabi==1.1.2
      - wcwidth==0.2.12
      - weasel==0.3.4
      - websocket-client==1.7.0
      - websockets==12.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - window-ops==0.0.14
      - wrapt==1.14.1
      - xgboost==2.0.3
      - xxhash==3.4.1
      - yarl==1.9.4
      - zict==3.0.0
      - zipp==3.17.0
prefix: /home/zxhuang/anaconda3/envs/cosork
