name: org_mech
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.1.0=gpu
  - absl-py=1.3.0=py37h06a4308_0
  - aiohttp=3.8.3=py37h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astor=0.8.1=py37h06a4308_0
  - async-timeout=4.0.2=py37h06a4308_0
  - asynctest=0.13.0=py_0
  - attrs=22.1.0=py37h06a4308_0
  - blas=1.0=mkl
  - blinker=1.4=py37h06a4308_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.15.1=py37h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py37h06a4308_0
  - cryptography=39.0.1=py37h9ce1e76_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - fftw=3.3.9=h27cfd23_1
  - flit-core=3.6.0=pyhd3eb1b0_0
  - frozenlist=1.3.3=py37h5eee18b_0
  - gast=0.2.2=py37_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.42.0=py37hce63b2e_0
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=h3ffc7dd_1
  - idna=3.4=py37h06a4308_0
  - importlib-metadata=4.11.3=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libprotobuf=3.20.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - markdown=3.4.1=py37h06a4308_0
  - markupsafe=2.1.1=py37h7f8727e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - multidict=6.0.2=py37h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - numpy=1.19.5=py37hd5178e2_4
  - numpy-base=1.19.5=py37h622ebfc_4
  - oauthlib=3.2.1=py37h06a4308_0
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - pip=22.3.1=py37h06a4308_0
  - protobuf=3.20.3=py37h6a678d5_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py37h06a4308_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pysocks=1.7.1=py37_1
  - python=3.7.10=h12debd9_4
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py37h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.7.3=py37h6c91a56_2
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tensorboard=2.10.0=py37h06a4308_0
  - tensorboard-data-server=0.6.1=py37h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py37h06a4308_0
  - tensorflow=2.1.0=gpu_py37h7a4bb67_0
  - tensorflow-base=2.1.0=gpu_py37h6c5654b_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - tensorflow-gpu=2.1.0=h0d30ee6_0
  - termcolor=2.1.0=py37h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - typing-extensions=4.4.0=py37h06a4308_0
  - typing_extensions=4.4.0=py37h06a4308_0
  - urllib3=1.26.14=py37h06a4308_0
  - werkzeug=2.2.2=py37h06a4308_0
  - wheel=0.38.4=py37h06a4308_0
  - wrapt=1.14.1=py37h5eee18b_0
  - xz=5.4.5=h5eee18b_0
  - yarl=1.8.1=py37h5eee18b_0
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - backcall==0.2.0
      - colorama==0.4.6
      - comm==0.1.4
      - cycler==0.11.0
      - debugpy==1.7.0
      - decorator==5.1.1
      - entrypoints==0.4
      - fonttools==4.38.0
      - future==0.18.3
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipywidgets==8.1.1
      - jedi==0.19.1
      - joblib==1.3.2
      - jupyter-client==7.4.9
      - jupyter-core==4.12.0
      - jupyterlab-widgets==3.0.9
      - keras==2.11.0
      - keras-tuner==1.0.1
      - kiwisolver==1.4.5
      - kt-legacy==1.0.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - nest-asyncio==1.5.8
      - packaging==23.2
      - pandas==1.3.5
      - parso==0.8.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - prompt-toolkit==3.0.41
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyzmq==25.1.2
      - scikit-learn==1.0.2
      - seaborn==0.12.2
      - tabulate==0.9.0
      - terminaltables==3.1.10
      - threadpoolctl==3.1.0
      - tornado==6.2
      - tqdm==4.66.1
      - traitlets==5.9.0
      - wcwidth==0.2.12
      - widgetsnbextension==4.0.9
prefix: ~/anaconda3/envs/org_mech
